aliases:
  - &python_settings
    types: [python]
    exclude: >
      (?x)^(
        .+/migrations/.+|
      )$

repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - <<: *python_settings
        id: isort

  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - <<: *python_settings
        id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - <<: *python_settings
        id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.770"
    hooks:
      - id: mypy
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        files: '^.*\.(py|mjml|js|jsx|tf|tfvars|conf)$'
