name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - run: pip install poetry
      - run: tox -e py
      - if: ${{ success() }}
        run: poetry build
      - if: ${{ success() }}
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
