name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install tox
      - run: tox -e py # Run tox using the version of Python in `PATH`
      - name: Persist coverage report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: ./coverage.xml
  report_coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Retreive coverage report
        uses: actions/download-artifact@v2
        with:
          name: test-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
